[features]
seeds = true
skip-lint = false

#
# Need to sync this in many files
#
# - here
# - lib.rs declare_id!
# - state.rs cardinal-reward-distributors
#
[programs.localnet]
soul_bound_authority = "7DkjPwuKxvz6Viiawtbmb4CqnMKP6eGb1WqYas1airUS"

[programs.mainnet]
soul_bound_authority = "7DkjPwuKxvz6Viiawtbmb4CqnMKP6eGb1WqYas1airUS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex-program-library/token-metadata/target/deploy/mpl_token_metadata.so"

#
# If this ever changes, make sure to change the
#
# - tests
# - program binary (declare id)
# - toml below
# - stake_programmable.rs inside the stake program.
#
[[test.genesis]]
address = "9zNbk2SZKniByFWH8tg3LKqkXy7myRU611SbJJgPt4gd"
program = "./deps/cardinal-staking/target/deploy/cardinal_reward_distributor.so"

#
# If this ever changes, make sure to change the
#
# - tests
# - program binary (declare id)
# - toml below
#
[[test.genesis]]
address = "49DZXCfSbfFRUHUEeeVwtHUrcaPsUGe7K2ke2wuttDim"
program = "./deps/cardinal-staking/target/deploy/cardinal_stake_pool.so"

#
# We clone the authorization rules program and the authorization rules account for
# local testing.
#
[test.validator]
url = "https://swr.xnfts.dev/rpc-proxy"

#
# Metaplex Authorization Rules program.
#
# If this ever changes, make sure to change the
#
# - tests
# - toml below
#
[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"

#
# Metaplex Authorization Rules account.
#
# If this ever changes, make sure to change the
#
# - tests
# - toml below
#
[[test.validator.clone]]
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"

#
# NFT #30 (Mad Lads #8925)
# Mint address
#
[[test.validator.clone]]
address = "3yYLEY3gPNHskKfyDZk3JRbDh7uSi1MKB3ffS9GEZXUJ"
#
# Associated Token Account address
#
[[test.validator.clone]]
address = "EzTUNAmoqj6FB7ygqTAMA3ttYEgyn9GAFUVm3mdYEgD"
#
# Token record.
#
[[test.validator.clone]]
address = "GB9AtxpkV8kSmWsdWzxTg5XTxi6igJHzdu85uz5VM2ww"
#
# Metadata Program Derived address
#
[[test.validator.clone]]
address = "CXxbKaC8FmdUrr32AhD2W6G9FgNBN8w2sPWwVuU2JwZV"
#
# Master Edition.
#
[[test.validator.clone]]
address = "5V4QUvLjtPfX8tjQncxw8UtPRxh9WHrAE5nVeuPxPvUz"

#
## NFT #15 (Mad Lads #9716)
# Mint address
#
[[test.validator.clone]]
address = "4B18U9PqtKFEwsHnZECyRewmh4zrFUo1Pxyf3Lwf1EMq"
#
# Associated Token Account address
#
[[test.validator.clone]]
address = "ERQD3CvzRe2RZJR7VJ3DPXZjA84A723CuaVM4f4RwtMF"
#
# Token record.
#
[[test.validator.clone]]
address = "4tgdRjrFZSKC3aHa8AADwQqhVZ83uCgSaKPgju5k21RZ"
#
# Metadata Program Derived address
#
[[test.validator.clone]]
address = "YUrTVSrA3FUJF5bF4awASUjd7nvvg9jv5urGitBxbPn"
#
# Master Edition.
#
[[test.validator.clone]]
address = "DwSMnFDJgUsDUwQXeC6Nd6NiUK1xkUfTzgAv7iB9LNFa"

#
# Mad Lads Collection NFT.
#
# Mint address
#
[[test.validator.clone]]
address = "J1S9H3QjnRtBbbuD4HjPV6RpRhwuk4zKbxsnCHuTgh9w"
#
# Metadata Program Derived address
#
[[test.validator.clone]]
address = "8KyuwGzav7jTW9YaBGj2Qtp2q24zPUR3rD5caojXaby4"
#
# Master Edition.
#
[[test.validator.clone]]
address = "2G5CotQ6Q87yhZxKUWkwLY6Foi12Q3VFQ6KN4nTLbPSz"
