[features]
seeds = true
skip-lint = false

[programs.localnet]
soul_bound_authority = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex-program-library/token-metadata/target/deploy/mpl_token_metadata.so"

#
# If this ever changes, make sure to change the
#
# - tests
# - program binary (declare id)
# - toml below
#
[[test.genesis]]
address = "rwdNPNPS6zNvtF6FMvaxPRjzu2eC51mXaDT9rmWsojp"
program = "./deps/cardinal-staking/target/deploy/cardinal_reward_distributor.so"

#
# If this ever changes, make sure to change the
#
# - tests
# - program binary (declare id)
# - toml below
#
[[test.genesis]]
address = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"
program = "./deps/cardinal-staking/target/deploy/cardinal_stake_pool.so"

#
# We clone the authorization rules program and the authorization rules account for
# local testing.
#
[test.validator]
url = "https://api.mainnet-beta.solana.com"

#
# Metaplex Authorization Rules program.
#
# If this ever changes, make sure to change the
#
# - tests
# - toml below
#
[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"

#
# Metaplex Authorization Rules account.
#
# If this ever changes, make sure to change the
#
# - tests
# - toml below
#
[[test.validator.clone]]
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"
